ALTER TABLE events ADD COLUMN photo_price DECIMAL(10,2) NOT NULL DEFAULT 20.00;
ALTER TABLE events ADD COLUMN pack_price DECIMAL(10,2) NOT NULL DEFAULT 65.00;
ALTER TABLE events ADD COLUMN free BOOLEAN NOT NULL DEFAULT false;
